apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-example
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
- apiGroups:
  - instana.com
  resources:
  - demos
  verbs:
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-example
subjects:
- kind: ServiceAccount
  name: operator-example
  namespace: default
roleRef:
  kind: ClusterRole
  name: operator-example
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-example
spec:
  selector:
    matchLabels:
      app: operator-example
  replicas: 1
  template:
    metadata:
      labels:
        app: operator-example
    spec:
      serviceAccountName: operator-example
      containers:
      - image: instana/operator-demo:2
        name: operator-example
        imagePullPolicy: IfNotPresent
